apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mynginxstatic
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mynginxstatic
    spec:
      containers:
      - name: mynginxstatic
        image: sjkpdk.azurecr.io/mynginxstatic:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: sjkpregistery
---
apiVersion: v1
kind: Service
metadata:
  name: mynginxstatic
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: mynginxstatic